-- Adds a composite index that covers workspace-wide aggregates filtered by
-- `status = 'ok'`. The existing `usage_events_lookup_btree`
-- (workspace_id, tenant_id, agent_id, ts) is useless for dashboard reads
-- that don't pin tenant_id / agent_id; most spend, calls, and tokens
-- panels look at the whole workspace.
--
-- Postgres inherits this on every partition (CREATE INDEX on a partitioned
-- parent fans out automatically on PG 11+).
--
-- OPERATIONAL NOTE: `usage_events` is partitioned. A plain CREATE INDEX on
-- the parent takes ACCESS EXCLUSIVE on every partition until each child
-- index finishes building, which can stall writes on a busy production
-- table. The safe form is CREATE INDEX CONCURRENTLY, but drizzle-kit runs
-- every migration inside a transaction and CONCURRENTLY is not allowed
-- inside one. Before applying this migration to production, run the index
-- build manually outside drizzle-kit:
--
--     CREATE INDEX CONCURRENTLY IF NOT EXISTS
--         usage_events_workspace_status_ts_idx
--         ON usage_events (workspace_id, status, ts);
--
-- Then mark the migration applied so drizzle-kit skips the in-transaction
-- form. The IF NOT EXISTS guard below makes the migration a no-op when
-- the index already exists.
CREATE INDEX IF NOT EXISTS usage_events_workspace_status_ts_idx
    ON usage_events (workspace_id, status, ts);
